# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with Unittest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_FROM_USER: ${{ secrets.EMAIL_FROM_USER }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ EMAIL_HOST_PASSWORD }}
          EMAIL_USE_TLS: ${{ EMAIL_USE_TLS }}
          EMAIL_PORT: ${{ EMAIL_PORT }}
          DB_NAME: ${{ DB_NAME }}
          DB_USER: ${{ DB_USER }}
          DB_PASSWORD: ${{ DB_PASSWORD }}
          DB_HOST: ${{ DB_HOST }}
          DB_PORT: ${{ DB_PORT }}
          DB_ENGINE: ${{ DB_ENGINE }}
        run: |
          python manage.py test
